pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                dir('jenkins') {
                    bat 'mvn clean package'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerapp = docker.build("docjv/jenkins_api:${env.BUILD_ID}", '-f jenkins/Dockerfile jenkins/')
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
    }
}
